In [7]:
# Getting Started with Pandas
# Objective: Introduce students to using Pandas for data analysis by loading data into Pandas
# DataFrames.

# Question 1: Importing Pandas and Loading a CSV File
# 1. Open your Jupyter Notebook or a Python environment.
# 2. Import the pandas library.
# 3. Load a CSV file into a DataFrame.




# Question 2: Displaying the First Few Rows
# 4. Use the head() method to display the first five rows of the DataFrame.





# Question 3: Basic Data Information
# 5. Use the info() method to get a concise summary of the DataFrame.

In [8]:
# Assuming 'df' is your loaded DataFrame

# Question 1: Inspecting Column Data Types
print(df.dtypes)


# Question 2: Selecting Columns
# Example: selecting the column named 'column_name'
selected_column = df['column_name']
print(selected_column)


# Question 3: Slicing Rows
# Example: select rows from index 2 to 5 (inclusive of 2, exclusive of 6)
sliced_rows = df[2:6]
print(sliced_rows)

NameError: name 'df' is not defined

In [ ]:
# Assuming 'df' is your loaded DataFrame

# Question 1: Inspecting Column Data Types
print(df.dtypes)

# Question 2: Selecting Columns
# Replace 'column_name' with your actual column name
selected_column = df['column_name']
print(selected_column)

# Question 3: Slicing Rows
# Select rows with index 2 up to but not including 6
sliced_rows = df[2:6]
print(sliced_rows)

In [ ]:
# Data Inspection & Selection
# Objective: Learn how to inspect data and select specific data points.

# Question 1: Inspecting Column Data Types
# 6. Use the dtypes attribute to inspect the data types of each column.




# Question 2: Selecting Columns
# 7. Select a single column from the DataFrame.





# Question 3: Slicing Rows
# 8. Select specific rows using slicing.

In [ ]:
# Assuming 'df' is your loaded DataFrame

# Question 1: Inspecting Column Data Types
print(df.dtypes)


# Question 2: Selecting Columns
# Example: selecting the column named 'column_name'
selected_column = df['column_name']
print(selected_column)


# Question 3: Slicing Rows
# Example: select rows from index 2 to 5 (inclusive of 2, exclusive of 6)
sliced_rows = df[2:6]
print(sliced_rows)

In [ ]:
# Assuming 'df' is your loaded DataFrame

# Question 1: Inspecting Column Data Types
print(df.dtypes)


# Question 2: Selecting Columns
# Example: selecting the column named 'column_name'
selected_column = df['column_name']
print(selected_column)


# Question 3: Slicing Rows
# Example: select rows from index 2 to 5 (inclusive of 2, exclusive of 6)
sliced_rows = df[2:6]
print(sliced_rows)

In [ ]:
# Assuming you already have a DataFrame 'df' loaded

# Question 1: Inspecting Column Data Types
print(df.dtypes)


# Question 2: Selecting Columns
# Select a single column by its name (replace 'column_name' with actual column)
single_column = df['column_name']
print(single_column)


# Question 3: Slicing Rows
# Select rows by slicing, e.g., rows 2 to 5 (index 2 inclusive to 5 exclusive)
subset_rows = df[2:6]
print(subset_rows)

In [ ]:
# Data Cleaning & Manipulation
# Objective: Practice cleaning data and manipulating DataFrames.

# Question 1: Handling Missing Values
# 9. Use the fillna() method to fill missing values with a specific value.




# QUestion 2: Renaming Columns
# 10. Change the names of specific columns using rename().




# Question 3: Dropping Duplicates
# 11. Remove duplicate rows from the DataFrame.

In [ ]:
# Data Aggregation & Exporting
# Objective: Aggregate data and export the results.

# Question 1: Grouping and Aggregating Data
# 12. Group data by a specific column and calculate the mean for each group.





# Question 2: Exporting Data to CSV
# 13. Export the DataFrame to a new CSV file.





# Question 3: Aggregating with Multiple Functions
# 14. Apply several aggregate functions to the grouped data.

In [ ]:
# Assuming 'df' is your loaded DataFrame

# Question 1: Grouping and Aggregating Data
# Replace 'group_column' with the column name you want to group by
grouped_mean = df.groupby('group_column').mean()
print(grouped_mean)


# Question 2: Exporting Data to CSV
# Export the grouped result or any DataFrame to CSV
grouped_mean.to_csv('grouped_mean_output.csv')


# Question 3: Aggregating with Multiple Functions
# Apply multiple aggregation functions to grouped data
grouped_agg = df.groupby('group_column').agg(['mean', 'sum', 'max', 'min'])
print(grouped_agg)