In [1]:
# Part 1: Load a Dataset & Check Missing Values

# Task 1: Titanic Dataset
# - Load the dataset using Pandas.
# - Check for missing values in the 'Age' column.







# Part 2: Identify Duplicates & Inconsistencies

# Task 2: Duplicate Rows in Titanic Dataset
# - Identify any duplicate rows in the dataset.










# Part 3: Generate a Data Quality Report

# Task 3: Titanic Dataset Overview
# - Create a simple report of missing values, duplicates, and some basic statistics for the Titanic dataset.

In [2]:
import pandas as pd

# Part 1: Load a Dataset & Check Missing Values

# Task 1: Load Titanic dataset
# If you don't have the dataset locally, you can load from seaborn as a quick example
import seaborn as sns
titanic = sns.load_dataset('titanic')

# Check missing values in 'age' column
missing_age_count = titanic['age'].isnull().sum()
print(f"Missing values in 'age' column: {missing_age_count}")



# Part 2: Identify Duplicates & Inconsistencies

# Task 2: Identify duplicate rows
duplicate_rows = titanic[titanic.duplicated()]
print(f"\nNumber of duplicate rows: {duplicate_rows.shape[0]}")



# Part 3: Generate a Data Quality Report

# Task 3: Summary report

def data_quality_report(df):
    print("\n--- Data Quality Report ---")
    # Missing values per column
    print("\nMissing values per column:")
    print(df.isnull().sum())
    
    # Duplicate rows count
    print(f"\nNumber of duplicate rows: {df.duplicated().sum()}")
    
    # Basic statistics summary for numerical columns
    print("\nBasic statistics (numerical columns):")
    print(df.describe())
    
    # Basic statistics summary for categorical columns
    print("\nBasic statistics (categorical columns):")
    print(df.describe(include=['object', 'category']))
    

data_quality_report(titanic)

Missing values in 'age' column: 177

Number of duplicate rows: 107

--- Data Quality Report ---

Missing values per column:
survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

Number of duplicate rows: 107

Basic statistics (numerical columns):
         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

Basic statistics (categorical columns):
         sex embarked  class  who deck  embark_town alive
count    891      889    891  891  203          889   891
unique     2        3      3    3    7            3     2
top     male        S  Third  man    C  Southampton    no
freq     577      644    491  537   59          644   549